# iPhone Purchase Prediction Using Logistic Regression
This project uses logistic regression to predict whether a customer will
purchase an iPhone based on age, salary, and gender.

## Machine Learning Task
Binary Classification

## Target Variable
- 0: The customer will not purchase an iPhone
- 1: The customer will purchase an iPhone

In [21]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report)

In [16]:
dataset = pd.read_csv("iphone_purchase.csv")
dataset.head()

   Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [17]:
print("Dataset shape:", dataset.shape)
print("\nDataset information:")
dataset.info()

print("\nMissing values:")
print(dataset.isnull().sum())

dataset.head()

Dataset shape: (400, 4)

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64
 2   Salary           400 non-null    int64
 3   Purchase Iphone  400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

Missing values:
Gender             0
Age                0
Salary             0
Purchase Iphone    0
dtype: int64

   Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [18]:
X = dataset. iloc[ :, : -1].values
y = dataset. iloc[ :, -1]. values
print(X[:4,:])

[['Male' 19 19000]
 ['Male' 35 20000]
 ['Female' 26 43000]
 ['Female' 27 57000]]

In [19]:
labelEncoder_gender = LabelEncoder()
X[:,0] = labelEncoder_gender.fit_transform(X[:,0])
print(X[:4,:])

[[1 19 19000]
 [1 35 20000]
 [0 26 43000]
 [0 27 57000]]

In [23]:
X = np.vstack(X[:, :]).astype(float)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [25]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
classifier = LogisticRegression(random_state=0, solver="liblinear")
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [27]:
y_pred = classifier.predict(X_test)

In [28]:
print(dataset.columns)
print(y[:10])
print(y.shape)
print(np.unique(y))

Index(['Gender', 'Age', 'Salary', 'Purchase Iphone'], dtype='object')
[0 0 0 0 0 0 0 1 0 0]
(400,)
[0 1]

In [29]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy score:", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision score:", precision)
recall = recall_score(y_test, y_pred)
print("Recall score:", recall)
fscore = f1_score(y_test, y_pred)
print("f1_score score:", fscore)

[[65  3]
 [ 6 26]]
Accuracy score: 0.91
Precision score: 0.896551724137931
Recall score: 0.8125
f1_score score: 0.8524590163934426

In [30]:
x1 = sc.transform([[1,21,40000]])
x2 = sc.transform([[1,21,80000]])
x3 = sc.transform([[0,21,40000]])
x4 = sc.transform([[0,21,80000]])
x5 = sc.transform([[1,41,40000]])
x6 = sc.transform([[1,41,80000]])
x7 = sc.transform([[0,41,40000]])
x8 = sc.transform([[0,68,80000]])
print("Male aged 21 making $40k will buy iPhone:", classifier.predict(x1))
print("Male aged 21 making $80k will buy iPhone:", classifier.predict(x2))
print("Female aged 21 making $40k will buy iPhone:", classifier.predict(x3))
print("Female aged 21 making $80k will buy iPhone:", classifier.predict(x4))
print("Male aged 41 making $40k will buy iPhone:", classifier.predict(x5))
print("Male aged 41 making $80k will buy iPhone:", classifier.predict(x6))
print("Female aged 41 making $40k will buy iPhone:", classifier.predict(x7))
print("Female aged 68 making $80k will buy iPhone:", classifier.predict(x8))

Male aged 21 making $40k will buy iPhone: [0]
Male aged 21 making $80k will buy iPhone: [0]
Female aged 21 making $40k will buy iPhone: [0]
Female aged 21 making $80k will buy iPhone: [0]
Male aged 41 making $40k will buy iPhone: [0]
Male aged 41 making $80k will buy iPhone: [1]
Female aged 41 making $40k will buy iPhone: [0]
Female aged 68 making $80k will buy iPhone: [1]